apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  labels:
    # https://github.com/prometheus-operator/prometheus-operator/issues/2119#issuecomment-439620190
    release: prometheus
spec:
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-nginx
